spring.application.name=DRIVEAWAY-BACKEND
server.port=2006

spring.data.mongodb.uri=mongodb+srv://charan:charan825@myatlasclusteredu.eqstcqn.mongodb.net/?appName=myAtlasClusterEDU
spring.data.mongodb.database=driveaway_db
spring.data.mongodb.auto-index-creation=true
spring.security.user.name=charan
spring.security.user.password=balayya

spring.cache.type=redis
spring.cache.redis.time-to-live=30000
spring.cache.redis.cache-null-values=false

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-wait=-1
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=8


