spring.application.name=DRIVEAWAY-BACKEND
server.port=2006

# MongoDB Configuration
spring.mongodb.uri=${DB_URL}
spring.mongodb.database=${DB_NAME}
spring.data.mongodb.auto-index-creation=true

# Razorpay Configuration
razorpay.keyId=${RZP_KEY}
razorpay.secret=${RZP_SECRET}

# Security Configuration
spring.security.user.name=charan
spring.security.user.password=charan

# Database Debugging
logging.level.com.mongodb.driver=DEBUG