spring.application.name=DRIVEAWAY-BACKEND
server.port=2006
spring.data.mongodb.uri=mongodb+srv://charan:charan825@myatlasclusteredu.eqstcqn.mongodb.net/?retryWrites=true&w=majority&appName=myAtlasClusterEDU
spring.data.mongodb.database=test_db