export const brandsArray = [
  { label: "Toyota", value: "Toyota", logo: "/images/toyota-logo.png" },
  { label: "Honda", value: "Honda", logo: "/images/honda-logo.png" },
  { label: "Chevrolet", value: "Chevrolet", logo: "/images/chevrolet-logo.png" },
  { label: "Ford", value: "Ford", logo: "/images/ford-logo.png" },
  { label: "Mercedes-Benz", value: "Mercedes-Benz", logo: "/images/mercedes-benz-logo.png" },
  { label: "Jeep", value: "Jeep", logo: "/images/jeep-logo.png" },
  { label: "BMW", value: "BMW", logo: "/images/bmw-logo.png" },
  { label: "Porsche", value: "Porsche", logo: "/images/porsche-logo.png" },
  { label: "Subaru", value: "Subaru", logo: "/images/subaru-logo.png" },
  { label: "Nissan", value: "Nissan", logo: "/images/nissan-logo.png" },
  { label: "Cadillac", value: "Cadillac", logo: "/images/cadillac-logo.png" },
  { label: "Volkswagen", value: "Volkswagen", logo: "/images/volkswagen-logo.png" },
  { label: "Lexus", value: "Lexus", logo: "/images/lexus-logo.png" },
  { label: "Audi", value: "Audi", logo: "/images/audi-logo.png" },
  { label: "Ferrari", value: "Ferrari", logo: "/images/ferrari-logo.png" },
  { label: "Volvo", value: "Volvo", logo: "/images/volvo-logo.png" },
  { label: "Jaguar", value: "Jaguar", logo: "/images/jaguar-logo.png" },
  { label: "GMC", value: "GMC", logo: "/images/gmc-logo.png" },
  { label: "Buick", value: "Buick", logo: "/images/buick-logo.png" },
  { label: "Acura", value: "Acura", logo: "/images/acura-logo.png" },
  { label: "Bentley", value: "Bentley", logo: "/images/bentley-logo.png" },
  { label: "Dodge", value: "Dodge", logo: "/images/dodge-logo.png" },
  { label: "Hyundai", value: "Hyundai", logo: "/images/hyundai-logo.png" },
  { label: "Lincoln", value: "Lincoln", logo: "/images/lincoln-logo.png" },
  { label: "Mazda", value: "Mazda", logo: "/images/mazda-logo.png" },
  { label: "Land Rover", value: "Land Rover", logo: "/images/land-rover-logo.png" },
  { label: "Tesla", value: "Tesla", logo: "/images/tesla-logo.png" },
  { label: "RAM", value: "RAM", logo: "/images/ram-logo.png" },
  { label: "Kia", value: "Kia", logo: "/images/kia-logo.png" },
  { label: "Chrysler", value: "Chrysler", logo: "/images/chrysler-logo.png" },
  { label: "Pontiac", value: "Pontiac", logo: "/images/pontiac-logo.png" },
  { label: "Infiniti", value: "Infiniti", logo: "/images/infiniti-logo.png" },
  { label: "Mitsubishi", value: "Mitsubishi", logo: "/images/mitsubishi-logo.png" },
  { label: "Oldsmobile", value: "Oldsmobile", logo: "/images/oldsmobile-logo.png" },
  { label: "Maserati", value: "Maserati", logo: "/images/maserati-logo.png" },
  { label: "Aston Martin", value: "Aston Martin", logo: "/images/aston-martin-logo.png" },
  { label: "Bugatti", value: "Bugatti", logo: "/images/bugatti-logo.png" },
  { label: "Fiat", value: "Fiat", logo: "/images/fiat-logo.png" },
  { label: "Mini", value: "Mini", logo: "/images/mini-logo.png" },
  { label: "Alfa Romeo", value: "Alfa Romeo", logo: "/images/alfa-romeo-logo.png" },
  { label: "Saab", value: "Saab", logo: "/images/saab-logo.png" },
  { label: "Genesis", value: "Genesis", logo: "/images/genesis-logo.png" },
  { label: "Suzuki", value: "Suzuki", logo: "/images/suzuki-logo.png" },
  { label: "Studebaker", value: "Studebaker", logo: "/images/studebaker-logo.png" },
  { label: "Renault", value: "Renault", logo: "/images/renault-logo.png" },
  { label: "Peugeot", value: "Peugeot", logo: "/images/peugeot-logo.png" },
  { label: "Daewoo", value: "Daewoo", logo: "/images/daewoo-logo.png" },
  { label: "Hudson", value: "Hudson", logo: "/images/hudson-logo.png" },
  { label: "Citroën", value: "Citroën", logo: "/images/citroen-logo.png" },
  { label: "MG", value: "MG", logo: "/images/mg-logo.png" }
];
